--- 
ribbon: 
  eureka: 
    enabled: false
server: 
  port: 8080
  ssl:
       enabled: false
       key-store: file:/home/SSL/abc.jks
       key-store-password: xyz
       key-password: xyz       
      
zuul:   
  prefix: /gateway/api
  routes: 
    employee-service: 
      path: /employee/**
      url: "http://localhost:8081/employee"
    department-service:  
      path: /department/**
      url: "http://localhost:8081/employee"